spring:
  data:
    mongodb:
      uri: mongodb+srv://nketu06:mYRyjWOFwFxndjwu@journal.zqm5j.mongodb.net/?retryWrites=true&w=majority&appName=journal
      database: journaldb
      auto-index-creation: true

  redis:
    host: localhost
    port: 6379

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nketu06@gmail.com
    password: cpwk ecey dobr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
weather:
  api-key: 8047318078042cc24a2c584b91ec81