spring:
  data:
    mongodb:
      uri: mongodb+srv://nketu06:mYRyjWOFwFxndjwu@journal.zqm5j.mongodb.net/?retryWrites=true&w=majority&appName=journal
      database: journaldb
      auto-index-creation: true

  main:
    allow-circular-references: true
weather:
  api-key: 8047318078042cc24a2c584b91ec81ed